# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7ed290283175ef1580f4c157486fbaf2e16be331a3738c8dcc0bd34e3a82e975b5eb7d4c21450e1bc6363d1efb3bf4deb3cc057b861f18eb027bf516b0282c5

test:
  secret_key_base: d696069ee9c29f643ae14d5e6cba5aa976c4ef70cc51509123788f2f79284ea8ce9f12ff65f29b46a81c9e6a8312b0d055107b4cb9f71fc4faf93b2f1293e7d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
